-- Legacy chat storage
-- 기존 채팅 메시지 테이블은 이전 데이터와 호환되도록 유지한다.
create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  character_id text not null,
  role text not null check (role in ('user', 'assistant')),
  content jsonb not null check (jsonb_typeof(content) = 'object')
);

create index if not exists idx_chat_messages_user_character_created_desc
  on public.chat_messages (user_id, character_id, created_at desc);

create index if not exists idx_chat_messages_user_created_desc
  on public.chat_messages (user_id, created_at desc);

alter table public.chat_messages enable row level security;

do $$ begin
  create policy "Users can view their own legacy messages"
    on public.chat_messages for select
    using (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can insert their own legacy messages"
    on public.chat_messages for insert
    with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can delete their own legacy messages"
    on public.chat_messages for delete
    using (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

-- Profiles / owner
-- 사용자 프로필과 owner 판정에 필요한 최소 설정을 먼저 준비한다.
create table if not exists public.profiles (
  user_id uuid primary key references auth.users on delete cascade,
  display_name text,
  avatar_url text,
  bio text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.profiles add column if not exists display_name text;
alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists bio text;
alter table public.profiles add column if not exists is_owner boolean not null default false;
alter table public.profiles add column if not exists updated_at timestamp with time zone default timezone('utc'::text, now()) not null;

alter table public.profiles enable row level security;

do $$ begin
  create policy "Users can read their own profile"
    on public.profiles for select
    using (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can write their own profile"
    on public.profiles for all
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

create table if not exists public.app_settings (
  key text primary key,
  value_json jsonb not null default '{}'::jsonb,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create or replace function public.is_owner_user()
returns boolean
language sql
stable
as $$
  with owner_setting as (
    select value_json
    from public.app_settings
    where key = 'owner_user_ids'
    limit 1
  )
  select
    coalesce((select p.is_owner from public.profiles p where p.user_id = auth.uid()), false)
    or exists (
      select 1
      from owner_setting s,
      lateral jsonb_array_elements_text(
        case
          when jsonb_typeof(s.value_json) = 'array' then s.value_json
          when jsonb_typeof(s.value_json) = 'object' and jsonb_typeof(s.value_json -> 'ids') = 'array' then s.value_json -> 'ids'
          else '[]'::jsonb
        end
      ) as owner_id(value)
      where owner_id.value = auth.uid()::text
    );
$$;

-- Characters
create table if not exists public.characters (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid references auth.users on delete cascade not null,
  slug text unique not null,
  name text not null,
  headline text,
  summary text not null default '',
  cover_image_url text,
  avatar_image_url text,
  visibility text not null default 'private' check (visibility in ('private','unlisted','public')),
  display_status text not null default 'draft' check (display_status in ('visible','hidden','draft')),
  source_type text not null default 'original' check (source_type in ('original','derivative')),
  tags text[] not null default '{}',
  profile_json jsonb not null default '{}'::jsonb,
  speech_style_json jsonb not null default '{}'::jsonb,
  prompt_profile_json jsonb not null default '{}'::jsonb,
  favorite_count integer not null default 0,
  chat_start_count integer not null default 0,
  published_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.characters add column if not exists owner_user_id uuid references auth.users on delete cascade;
alter table public.characters add column if not exists slug text;
alter table public.characters add column if not exists name text;
alter table public.characters add column if not exists headline text;
alter table public.characters add column if not exists summary text not null default '';
alter table public.characters add column if not exists cover_image_url text;
alter table public.characters add column if not exists avatar_image_url text;
alter table public.characters add column if not exists visibility text not null default 'private';
alter table public.characters add column if not exists display_status text not null default 'draft';
alter table public.characters add column if not exists source_type text not null default 'original';
alter table public.characters add column if not exists tags text[] not null default '{}';
alter table public.characters add column if not exists profile_json jsonb not null default '{}'::jsonb;
alter table public.characters add column if not exists speech_style_json jsonb not null default '{}'::jsonb;
alter table public.characters add column if not exists prompt_profile_json jsonb not null default '{}'::jsonb;
alter table public.characters add column if not exists favorite_count integer not null default 0;
alter table public.characters add column if not exists chat_start_count integer not null default 0;
alter table public.characters add column if not exists published_at timestamp with time zone;
alter table public.characters add column if not exists updated_at timestamp with time zone default timezone('utc'::text, now()) not null;

create index if not exists idx_characters_owner_updated on public.characters (owner_user_id, updated_at desc);
create index if not exists idx_characters_visible_updated on public.characters (display_status, updated_at desc);

alter table public.characters enable row level security;

do $$ begin
  create policy "Public can read visible characters or owners can read their own"
    on public.characters for select
    using ((visibility = 'public' and display_status = 'visible') or auth.uid() = owner_user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can insert their own characters"
    on public.characters for insert
    with check (auth.uid() = owner_user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can update their own characters"
    on public.characters for update
    using (auth.uid() = owner_user_id)
    with check (auth.uid() = owner_user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Owner users can manage all characters"
    on public.characters for all
    using (public.is_owner_user())
    with check (public.is_owner_user());
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can delete their own characters"
    on public.characters for delete
    using (auth.uid() = owner_user_id or public.is_owner_user());
exception when duplicate_object then null; end $$;

-- Worlds
create table if not exists public.worlds (
  id uuid primary key default gen_random_uuid(),
  owner_user_id uuid references auth.users on delete cascade not null,
  slug text unique not null,
  name text not null,
  headline text,
  summary text not null default '',
  cover_image_url text,
  visibility text not null default 'private' check (visibility in ('private','unlisted','public')),
  display_status text not null default 'draft' check (display_status in ('visible','hidden','draft')),
  source_type text not null default 'original' check (source_type in ('original','derivative')),
  tags text[] not null default '{}',
  world_rules_markdown text,
  prompt_profile_json jsonb not null default '{}'::jsonb,
  favorite_count integer not null default 0,
  chat_start_count integer not null default 0,
  published_at timestamp with time zone,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.worlds add column if not exists owner_user_id uuid references auth.users on delete cascade;
alter table public.worlds add column if not exists slug text;
alter table public.worlds add column if not exists name text;
alter table public.worlds add column if not exists headline text;
alter table public.worlds add column if not exists summary text not null default '';
alter table public.worlds add column if not exists cover_image_url text;
alter table public.worlds add column if not exists visibility text not null default 'private';
alter table public.worlds add column if not exists display_status text not null default 'draft';
alter table public.worlds add column if not exists source_type text not null default 'original';
alter table public.worlds add column if not exists tags text[] not null default '{}';
alter table public.worlds add column if not exists world_rules_markdown text;
alter table public.worlds add column if not exists prompt_profile_json jsonb not null default '{}'::jsonb;
alter table public.worlds add column if not exists favorite_count integer not null default 0;
alter table public.worlds add column if not exists chat_start_count integer not null default 0;
alter table public.worlds add column if not exists published_at timestamp with time zone;
alter table public.worlds add column if not exists updated_at timestamp with time zone default timezone('utc'::text, now()) not null;

create index if not exists idx_worlds_owner_updated on public.worlds (owner_user_id, updated_at desc);
create index if not exists idx_worlds_visible_updated on public.worlds (display_status, updated_at desc);

alter table public.worlds enable row level security;

do $$ begin
  create policy "Public can read visible worlds or owners can read their own"
    on public.worlds for select
    using ((visibility = 'public' and display_status = 'visible') or auth.uid() = owner_user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can insert their own worlds"
    on public.worlds for insert
    with check (auth.uid() = owner_user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can update their own worlds"
    on public.worlds for update
    using (auth.uid() = owner_user_id)
    with check (auth.uid() = owner_user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Owner users can manage all worlds"
    on public.worlds for all
    using (public.is_owner_user())
    with check (public.is_owner_user());
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can delete their own worlds"
    on public.worlds for delete
    using (auth.uid() = owner_user_id or public.is_owner_user());
exception when duplicate_object then null; end $$;

-- Rooms / messages / state
create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users on delete cascade not null,
  character_id uuid references public.characters on delete set null,
  world_id uuid references public.worlds on delete set null,
  user_alias text not null default '나',
  title text not null,
  bridge_profile_json jsonb not null default '{}'::jsonb,
  resolved_prompt_snapshot_json jsonb not null default '{}'::jsonb,
  last_message_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.rooms add column if not exists user_alias text not null default '나';
alter table public.rooms add column if not exists title text not null default '';
alter table public.rooms add column if not exists bridge_profile_json jsonb not null default '{}'::jsonb;
alter table public.rooms add column if not exists resolved_prompt_snapshot_json jsonb not null default '{}'::jsonb;
alter table public.rooms add column if not exists last_message_at timestamp with time zone default timezone('utc'::text, now()) not null;
alter table public.rooms add column if not exists created_at timestamp with time zone default timezone('utc'::text, now()) not null;
alter table public.rooms add column if not exists updated_at timestamp with time zone default timezone('utc'::text, now()) not null;
alter table public.rooms alter column character_id drop not null;
alter table public.rooms alter column world_id drop not null;

do $$ begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'rooms'
      and column_name = 'preset_id'
  ) then
    execute 'alter table public.rooms alter column preset_id drop not null';
  end if;
end $$;

create index if not exists idx_rooms_user_updated on public.rooms (user_id, updated_at desc);

alter table public.rooms enable row level security;

do $$ begin
  create policy "Users can read their own rooms"
    on public.rooms for select
    using (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can insert their own rooms"
    on public.rooms for insert
    with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can update their own rooms"
    on public.rooms for update
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

create table if not exists public.room_messages (
  id uuid primary key default gen_random_uuid(),
  room_id uuid references public.rooms on delete cascade not null,
  role text not null check (role in ('user','assistant')),
  content_json jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.room_messages add column if not exists role text;
alter table public.room_messages add column if not exists content_json jsonb not null default '{}'::jsonb;
alter table public.room_messages add column if not exists created_at timestamp with time zone default timezone('utc'::text, now()) not null;

create index if not exists idx_room_messages_room_created on public.room_messages (room_id, created_at asc);

alter table public.room_messages enable row level security;

do $$ begin
  create policy "Users can read messages in their own rooms"
    on public.room_messages for select
    using (exists (select 1 from public.rooms where rooms.id = room_messages.room_id and rooms.user_id = auth.uid()));
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can insert messages in their own rooms"
    on public.room_messages for insert
    with check (exists (select 1 from public.rooms where rooms.id = room_messages.room_id and rooms.user_id = auth.uid()));
exception when duplicate_object then null; end $$;

create table if not exists public.room_state_summaries (
  room_id uuid primary key references public.rooms on delete cascade,
  current_situation text,
  location text,
  relationship_state text,
  inventory_json jsonb not null default '[]'::jsonb,
  appearance_json jsonb not null default '[]'::jsonb,
  pose_json jsonb not null default '[]'::jsonb,
  future_promises_json jsonb not null default '[]'::jsonb,
  world_notes_json jsonb not null default '[]'::jsonb,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.room_state_summaries add column if not exists current_situation text;
alter table public.room_state_summaries add column if not exists location text;
alter table public.room_state_summaries add column if not exists relationship_state text;
alter table public.room_state_summaries add column if not exists inventory_json jsonb not null default '[]'::jsonb;
alter table public.room_state_summaries add column if not exists appearance_json jsonb not null default '[]'::jsonb;
alter table public.room_state_summaries add column if not exists pose_json jsonb not null default '[]'::jsonb;
alter table public.room_state_summaries add column if not exists future_promises_json jsonb not null default '[]'::jsonb;
alter table public.room_state_summaries add column if not exists world_notes_json jsonb not null default '[]'::jsonb;
alter table public.room_state_summaries add column if not exists updated_at timestamp with time zone default timezone('utc'::text, now()) not null;

alter table public.room_state_summaries enable row level security;

do $$ begin
  create policy "Users can read room state summaries in their own rooms"
    on public.room_state_summaries for select
    using (exists (select 1 from public.rooms where rooms.id = room_state_summaries.room_id and rooms.user_id = auth.uid()));
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can write room state summaries in their own rooms"
    on public.room_state_summaries for all
    using (exists (select 1 from public.rooms where rooms.id = room_state_summaries.room_id and rooms.user_id = auth.uid()))
    with check (exists (select 1 from public.rooms where rooms.id = room_state_summaries.room_id and rooms.user_id = auth.uid()));
exception when duplicate_object then null; end $$;

-- Bookmarks / recent views
create table if not exists public.bookmarks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users on delete cascade not null,
  target_type text not null check (target_type in ('character','world')),
  target_id uuid not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create unique index if not exists idx_bookmarks_user_target_unique on public.bookmarks (user_id, target_type, target_id);

alter table public.bookmarks enable row level security;

do $$ begin
  create policy "Users can manage their own bookmarks"
    on public.bookmarks for all
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

create table if not exists public.recent_views (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users on delete cascade not null,
  target_type text not null check (target_type in ('character','world')),
  target_id uuid not null,
  viewed_at timestamp with time zone default timezone('utc'::text, now()) not null
);

with ranked_recent_views as (
  select
    ctid,
    row_number() over (
      partition by user_id, target_type, target_id
      order by viewed_at desc, id desc
    ) as rn
  from public.recent_views
)
delete from public.recent_views rv
using ranked_recent_views ranked
where rv.ctid = ranked.ctid
  and ranked.rn > 1;

create unique index if not exists idx_recent_views_user_target_unique
  on public.recent_views (user_id, target_type, target_id);

create index if not exists idx_recent_views_user_viewed on public.recent_views (user_id, viewed_at desc);

alter table public.recent_views enable row level security;

do $$ begin
  create policy "Users can manage their own recent views"
    on public.recent_views for all
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);
exception when duplicate_object then null; end $$;

-- Assets / storage
create table if not exists public.character_assets (
  id uuid primary key default gen_random_uuid(),
  character_id uuid references public.characters on delete cascade not null,
  asset_kind text not null check (asset_kind in ('thumb','card','detail','gallery')),
  url text not null,
  width integer,
  height integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_character_assets_character_kind on public.character_assets (character_id, asset_kind);

alter table public.character_assets enable row level security;

do $$ begin
  create policy "Public can read assets of visible public characters or owners can read their own"
    on public.character_assets for select
    using (
      exists (
        select 1 from public.characters c
        where c.id = character_assets.character_id
          and ((c.visibility = 'public' and c.display_status = 'visible') or c.owner_user_id = auth.uid())
      )
    );
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can insert their own character assets"
    on public.character_assets for insert
    with check (
      exists (
        select 1 from public.characters c
        where c.id = character_assets.character_id
          and c.owner_user_id = auth.uid()
      )
    );
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can update their own character assets"
    on public.character_assets for update
    using (
      exists (
        select 1 from public.characters c
        where c.id = character_assets.character_id
          and c.owner_user_id = auth.uid()
      )
    )
    with check (
      exists (
        select 1 from public.characters c
        where c.id = character_assets.character_id
          and c.owner_user_id = auth.uid()
      )
    );
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can delete their own character assets"
    on public.character_assets for delete
    using (
      exists (
        select 1 from public.characters c
        where c.id = character_assets.character_id
          and c.owner_user_id = auth.uid()
      )
    );
exception when duplicate_object then null; end $$;

create table if not exists public.world_assets (
  id uuid primary key default gen_random_uuid(),
  world_id uuid references public.worlds on delete cascade not null,
  asset_kind text not null check (asset_kind in ('thumb','card','hero','gallery')),
  url text not null,
  width integer,
  height integer,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists idx_world_assets_world_kind on public.world_assets (world_id, asset_kind);

alter table public.world_assets enable row level security;

do $$ begin
  create policy "Public can read assets of visible public worlds or owners can read their own"
    on public.world_assets for select
    using (
      exists (
        select 1 from public.worlds w
        where w.id = world_assets.world_id
          and ((w.visibility = 'public' and w.display_status = 'visible') or w.owner_user_id = auth.uid())
      )
    );
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can insert their own world assets"
    on public.world_assets for insert
    with check (
      exists (
        select 1 from public.worlds w
        where w.id = world_assets.world_id
          and w.owner_user_id = auth.uid()
      )
    );
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can update their own world assets"
    on public.world_assets for update
    using (
      exists (
        select 1 from public.worlds w
        where w.id = world_assets.world_id
          and w.owner_user_id = auth.uid()
      )
    )
    with check (
      exists (
        select 1 from public.worlds w
        where w.id = world_assets.world_id
          and w.owner_user_id = auth.uid()
      )
    );
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Users can delete their own world assets"
    on public.world_assets for delete
    using (
      exists (
        select 1 from public.worlds w
        where w.id = world_assets.world_id
          and w.owner_user_id = auth.uid()
      )
    );
exception when duplicate_object then null; end $$;

-- App settings / seed values
-- 하단 설정은 운영 초기 상태와 공개 자산 정책을 같은 파일에서 마무리한다.
create table if not exists public.app_settings (
  key text primary key,
  value_json jsonb not null default '{}'::jsonb,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.app_settings add column if not exists value_json jsonb not null default '{}'::jsonb;
alter table public.app_settings add column if not exists updated_at timestamp with time zone default timezone('utc'::text, now()) not null;
alter table public.app_settings enable row level security;

do $$ begin
  create policy "Public can read app settings"
    on public.app_settings for select
    using (true);
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Owner users can write app settings"
    on public.app_settings for all
    using (public.is_owner_user())
    with check (public.is_owner_user());
exception when duplicate_object then null; end $$;

insert into public.app_settings (key, value_json)
values ('owner_user_ids', '[]'::jsonb)
on conflict (key) do nothing;

insert into public.app_settings (key, value_json)
values ('home.hero', jsonb_build_object('mode', 'auto', 'targetPath', '/characters/mika'))
on conflict (key) do nothing;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'vmate-assets',
  'vmate-assets',
  true,
  8388608,
  array['image/png', 'image/jpeg', 'image/webp', 'image/avif']
)
on conflict (id) do nothing;

-- Public buckets serve object URLs without a SELECT policy; removing it prevents file listing.
drop policy if exists "Public can read vmate assets" on storage.objects;

do $$ begin
  create policy "Authenticated users can upload vmate assets to their own folder"
    on storage.objects for insert
    with check (
      bucket_id = 'vmate-assets'
      and split_part(name, '/' , 1) = auth.uid()::text
    );
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Authenticated users can update vmate assets in their own folder"
    on storage.objects for update
    using (
      bucket_id = 'vmate-assets'
      and split_part(name, '/' , 1) = auth.uid()::text
    )
    with check (
      bucket_id = 'vmate-assets'
      and split_part(name, '/' , 1) = auth.uid()::text
    );
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "Authenticated users can delete vmate assets in their own folder"
    on storage.objects for delete
    using (
      bucket_id = 'vmate-assets'
      and split_part(name, '/' , 1) = auth.uid()::text
    );
exception when duplicate_object then null; end $$;


-- V-MATE B2C hardening: owner isolation, UGC reports, and daily chat quota.
-- Review in a staging project before applying. This migration does not delete existing content.

alter table public.profiles add column if not exists handle text;
create unique index if not exists profiles_handle_unique on public.profiles (lower(handle)) where handle is not null;

create table if not exists public.owner_users (
  user_id uuid primary key references auth.users on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

insert into public.owner_users (user_id)
select user_id from public.profiles where is_owner is true
on conflict (user_id) do nothing;

insert into public.owner_users (user_id)
select owner_id.value::uuid
from public.app_settings settings,
lateral jsonb_array_elements_text(
  case
    when jsonb_typeof(settings.value_json) = 'array' then settings.value_json
    when jsonb_typeof(settings.value_json) = 'object' and jsonb_typeof(settings.value_json -> 'ids') = 'array' then settings.value_json -> 'ids'
    else '[]'::jsonb
  end
) as owner_id(value)
where settings.key = 'owner_user_ids'
  and owner_id.value ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
on conflict (user_id) do nothing;

update public.profiles set is_owner = false where is_owner is true;

alter table public.owner_users enable row level security;

create or replace function public.is_owner_user()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select auth.uid() is not null and exists (
    select 1 from public.owner_users where user_id = auth.uid()
  );
$$;

revoke all on function public.is_owner_user() from public;
grant execute on function public.is_owner_user() to anon, authenticated;

drop policy if exists "Owner users can read owner roles" on public.owner_users;
create policy "Owner users can read owner roles" on public.owner_users for select using (public.is_owner_user());
drop policy if exists "Owner users can manage owner roles" on public.owner_users;
create policy "Owner users can manage owner roles" on public.owner_users for all using (public.is_owner_user()) with check (public.is_owner_user());

drop policy if exists "Users can read their own profile" on public.profiles;
drop policy if exists "Users can write their own profile" on public.profiles;
drop policy if exists "Public can read creator profiles" on public.profiles;
drop policy if exists "Users can insert their own profile" on public.profiles;
drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Public can read creator profiles" on public.profiles for select using (auth.uid() = user_id or public.is_owner_user());
create policy "Users can insert their own profile" on public.profiles for insert with check (auth.uid() = user_id and is_owner is false);
create policy "Users can update their own profile" on public.profiles for update using (auth.uid() = user_id) with check (auth.uid() = user_id and is_owner is false);

revoke insert, update on public.profiles from anon, authenticated;
grant insert (user_id, handle, display_name, avatar_url, bio, updated_at) on public.profiles to authenticated;
grant update (handle, display_name, avatar_url, bio, updated_at) on public.profiles to authenticated;

create or replace function public.handle_new_profile()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.profiles (user_id, handle, display_name)
  values (
    new.id,
    'user_' || left(replace(new.id::text, '-', ''), 12),
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'name'), ''), '사용자')
  )
  on conflict (user_id) do nothing;
  return new;
exception when others then
  return new;
end;
$$;

drop trigger if exists on_auth_user_created_create_profile on auth.users;
create trigger on_auth_user_created_create_profile after insert on auth.users for each row execute procedure public.handle_new_profile();

drop policy if exists "Public can read app settings" on public.app_settings;
create policy "Public can read non-sensitive app settings" on public.app_settings for select using (key <> 'owner_user_ids');

alter table public.characters add column if not exists source_url text;
alter table public.characters add column if not exists rights_attested_at timestamp with time zone;
alter table public.worlds add column if not exists source_url text;
alter table public.worlds add column if not exists rights_attested_at timestamp with time zone;

create table if not exists public.content_moderation (
  entity_type text not null check (entity_type in ('character', 'world')),
  entity_id uuid not null,
  status text not null default 'clear' check (status in ('clear', 'quarantined', 'blocked')),
  reason text not null default '',
  actioned_by uuid references auth.users on delete set null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (entity_type, entity_id)
);

create table if not exists public.content_reports (
  id uuid primary key default gen_random_uuid(),
  reporter_user_id uuid references auth.users on delete cascade not null,
  entity_type text not null check (entity_type in ('character', 'world')),
  entity_id uuid not null,
  entity_name text not null default '',
  reason text not null check (reason in ('sexual_content', 'minor_safety', 'hate_or_harassment', 'copyright', 'spam', 'other')),
  details text not null default '' check (char_length(details) <= 1000),
  status text not null default 'open' check (status in ('open', 'dismissed', 'actioned')),
  reviewed_by uuid references auth.users on delete set null,
  review_note text not null default '',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  reviewed_at timestamp with time zone
);

create unique index if not exists content_reports_one_open_per_reporter
  on public.content_reports (reporter_user_id, entity_type, entity_id) where status = 'open';
create index if not exists content_reports_status_created on public.content_reports (status, created_at desc);

create table if not exists public.content_moderation_actions (
  id uuid primary key default gen_random_uuid(),
  report_id uuid references public.content_reports on delete set null,
  entity_type text not null check (entity_type in ('character', 'world')),
  entity_id uuid not null,
  action text not null check (action in ('auto_quarantine', 'dismiss', 'restore', 'quarantine', 'remove')),
  note text not null default '' check (char_length(note) <= 1000),
  actioned_by uuid references auth.users on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
create index if not exists content_moderation_actions_entity_created
  on public.content_moderation_actions (entity_type, entity_id, created_at desc);

alter table public.content_moderation enable row level security;
alter table public.content_reports enable row level security;
alter table public.content_moderation_actions enable row level security;

create or replace function public.validate_content_report_target()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  target_name text;
begin
  if new.entity_type = 'character' then
    select name into target_name from public.characters
    where id = new.entity_id and visibility = 'public' and display_status = 'visible'
      and not exists (select 1 from public.content_moderation where entity_type = 'character' and entity_id = new.entity_id and status in ('quarantined', 'blocked'));
  elsif new.entity_type = 'world' then
    select name into target_name from public.worlds
    where id = new.entity_id and visibility = 'public' and display_status = 'visible'
      and not exists (select 1 from public.content_moderation where entity_type = 'world' and entity_id = new.entity_id and status in ('quarantined', 'blocked'));
  end if;
  if target_name is null then raise exception 'REPORT_TARGET_NOT_FOUND' using errcode = '23503'; end if;
  new.entity_name := target_name;
  return new;
end;
$$;

drop trigger if exists validate_content_report_target on public.content_reports;
create trigger validate_content_report_target before insert on public.content_reports for each row execute procedure public.validate_content_report_target();

drop policy if exists "Users can create content reports" on public.content_reports;
create policy "Users can create content reports" on public.content_reports for insert with check (auth.uid() = reporter_user_id);
drop policy if exists "Users can read their reports" on public.content_reports;
create policy "Users can read their reports" on public.content_reports for select using (auth.uid() = reporter_user_id or public.is_owner_user());
drop policy if exists "Owner users can manage content reports" on public.content_reports;
create policy "Owner users can manage content reports" on public.content_reports for all using (public.is_owner_user()) with check (public.is_owner_user());
drop policy if exists "Owner users can manage moderation" on public.content_moderation;
create policy "Owner users can manage moderation" on public.content_moderation for all using (public.is_owner_user()) with check (public.is_owner_user());
drop policy if exists "Owner users can read moderation actions" on public.content_moderation_actions;
create policy "Owner users can read moderation actions" on public.content_moderation_actions for select using (public.is_owner_user());
revoke all on public.content_moderation_actions from anon, authenticated;
grant select on public.content_moderation_actions to authenticated;

create or replace function public.is_content_publicly_allowed(p_entity_type text, p_entity_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select not exists (
    select 1 from public.content_moderation
    where entity_type = p_entity_type and entity_id = p_entity_id and status in ('quarantined', 'blocked')
  );
$$;
revoke all on function public.is_content_publicly_allowed(text, uuid) from public;
grant execute on function public.is_content_publicly_allowed(text, uuid) to anon, authenticated;

create or replace function public.quarantine_content_after_reports()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  reporter_count integer;
  current_status text;
begin
  select count(distinct reporter_user_id) into reporter_count
  from public.content_reports
  where entity_type = new.entity_type and entity_id = new.entity_id and status = 'open';
  select status into current_status from public.content_moderation where entity_type = new.entity_type and entity_id = new.entity_id;
  if reporter_count >= 3 and coalesce(current_status, 'clear') not in ('quarantined', 'blocked') then
    insert into public.content_moderation (entity_type, entity_id, status, reason, updated_at)
    values (new.entity_type, new.entity_id, 'quarantined', 'report_threshold', timezone('utc'::text, now()))
    on conflict (entity_type, entity_id) do update
      set status = case when public.content_moderation.status = 'blocked' then 'blocked' else 'quarantined' end,
          reason = case when public.content_moderation.status = 'blocked' then public.content_moderation.reason else 'report_threshold' end,
          updated_at = timezone('utc'::text, now());
    insert into public.content_moderation_actions (report_id, entity_type, entity_id, action, note)
    values (new.id, new.entity_type, new.entity_id, 'auto_quarantine', 'report_threshold');
  end if;
  return new;
end;
$$;

drop trigger if exists quarantine_content_after_reports on public.content_reports;
create trigger quarantine_content_after_reports after insert on public.content_reports for each row execute procedure public.quarantine_content_after_reports();

drop policy if exists "Public can read visible characters or owners can read their own" on public.characters;
create policy "Public can read unmoderated visible characters or owners can read their own" on public.characters for select using (
  auth.uid() = owner_user_id or (
    visibility = 'public' and display_status = 'visible' and public.is_content_publicly_allowed('character', characters.id)
  )
);
drop policy if exists "Public can read visible worlds or owners can read their own" on public.worlds;
create policy "Public can read unmoderated visible worlds or owners can read their own" on public.worlds for select using (
  auth.uid() = owner_user_id or (
    visibility = 'public' and display_status = 'visible' and public.is_content_publicly_allowed('world', worlds.id)
  )
);

drop policy if exists "Users can insert their own characters" on public.characters;
create policy "Users can insert their own characters" on public.characters for insert with check (
  auth.uid() = owner_user_id and (visibility <> 'public' or rights_attested_at is not null)
);
drop policy if exists "Users can update their own characters" on public.characters;
create policy "Users can update their own characters" on public.characters for update using (auth.uid() = owner_user_id) with check (
  auth.uid() = owner_user_id and (visibility <> 'public' or rights_attested_at is not null)
);
drop policy if exists "Users can insert their own worlds" on public.worlds;
create policy "Users can insert their own worlds" on public.worlds for insert with check (
  auth.uid() = owner_user_id and (visibility <> 'public' or rights_attested_at is not null)
);
drop policy if exists "Users can update their own worlds" on public.worlds;
create policy "Users can update their own worlds" on public.worlds for update using (auth.uid() = owner_user_id) with check (
  auth.uid() = owner_user_id and (visibility <> 'public' or rights_attested_at is not null)
);

create or replace function public.apply_content_report_action(p_report_id uuid, p_action text, p_note text default '')
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  target public.content_reports%rowtype;
  next_status text := 'clear';
begin
  if not public.is_owner_user() then raise exception 'OWNER_FORBIDDEN' using errcode = '42501'; end if;
  select * into target from public.content_reports where id = p_report_id for update;
  if not found then return null; end if;
  if p_action = 'dismiss' then
    update public.content_reports set status = 'dismissed', reviewed_by = auth.uid(), review_note = left(coalesce(p_note, ''), 1000), reviewed_at = timezone('utc'::text, now()) where id = p_report_id;
  elsif p_action = 'restore' then
    insert into public.content_moderation (entity_type, entity_id, status, reason, actioned_by, updated_at)
    values (target.entity_type, target.entity_id, 'clear', 'owner_restore', auth.uid(), timezone('utc'::text, now()))
    on conflict (entity_type, entity_id) do update set status = 'clear', reason = 'owner_restore', actioned_by = auth.uid(), updated_at = timezone('utc'::text, now());
    update public.content_reports set status = 'dismissed', reviewed_by = auth.uid(), review_note = left(coalesce(p_note, ''), 1000), reviewed_at = timezone('utc'::text, now()) where entity_type = target.entity_type and entity_id = target.entity_id and status = 'open';
  elsif p_action in ('quarantine', 'remove') then
    next_status := case when p_action = 'remove' then 'blocked' else 'quarantined' end;
    insert into public.content_moderation (entity_type, entity_id, status, reason, actioned_by, updated_at)
    values (target.entity_type, target.entity_id, next_status, 'owner_' || p_action, auth.uid(), timezone('utc'::text, now()))
    on conflict (entity_type, entity_id) do update set status = excluded.status, reason = excluded.reason, actioned_by = auth.uid(), updated_at = timezone('utc'::text, now());
    update public.content_reports set status = 'actioned', reviewed_by = auth.uid(), review_note = left(coalesce(p_note, ''), 1000), reviewed_at = timezone('utc'::text, now()) where id = p_report_id;
  else
    raise exception 'INVALID_MODERATION_ACTION' using errcode = '22023';
  end if;
  select coalesce(status, 'clear') into next_status from public.content_moderation where entity_type = target.entity_type and entity_id = target.entity_id;
  next_status := coalesce(next_status, 'clear');
  insert into public.content_moderation_actions (report_id, entity_type, entity_id, action, note, actioned_by)
  values (target.id, target.entity_type, target.entity_id, p_action, left(coalesce(p_note, ''), 1000), auth.uid());
  return jsonb_build_object('reportId', p_report_id, 'moderationStatus', next_status, 'action', p_action);
end;
$$;
revoke all on function public.apply_content_report_action(uuid, text, text) from public;
grant execute on function public.apply_content_report_action(uuid, text, text) to authenticated;

create table if not exists public.chat_usage_daily (
  user_id uuid references auth.users on delete cascade not null,
  usage_date date not null,
  used_count integer not null default 0 check (used_count >= 0),
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  primary key (user_id, usage_date)
);
create table if not exists public.chat_usage_events (
  request_id text not null,
  user_id uuid references auth.users on delete cascade not null,
  usage_date date not null,
  status text not null check (status in ('reserved', 'completed', 'refunded')),
  response_json jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  completed_at timestamp with time zone,
  refunded_at timestamp with time zone,
  primary key (user_id, request_id)
);
alter table public.chat_usage_events add column if not exists response_json jsonb;
alter table public.chat_usage_events add column if not exists completed_at timestamp with time zone;
alter table public.chat_usage_events drop constraint if exists chat_usage_events_pkey;
alter table public.chat_usage_events add constraint chat_usage_events_pkey primary key (user_id, request_id);
alter table public.chat_usage_events drop constraint if exists chat_usage_events_status_check;
alter table public.chat_usage_events add constraint chat_usage_events_status_check check (status in ('reserved', 'completed', 'refunded'));
alter table public.chat_usage_daily enable row level security;
alter table public.chat_usage_events enable row level security;
drop policy if exists "Users can read their daily chat usage" on public.chat_usage_daily;
create policy "Users can read their daily chat usage" on public.chat_usage_daily for select using (auth.uid() = user_id);
drop policy if exists "Users can read their chat usage events" on public.chat_usage_events;
create policy "Users can read their chat usage events" on public.chat_usage_events for select using (auth.uid() = user_id);
revoke insert, update, delete on public.chat_usage_daily from authenticated;
revoke insert, update, delete on public.chat_usage_events from authenticated;

create or replace function public.get_daily_chat_quota(p_limit integer default 30)
returns table(message_limit integer, remaining integer, reset_at timestamp with time zone)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  current_date_kst date := timezone('Asia/Seoul', now())::date;
  used integer := 0;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED' using errcode = '42501'; end if;
  p_limit := greatest(1, least(coalesce(p_limit, 30), 500));
  select used_count into used from public.chat_usage_daily where user_id = auth.uid() and usage_date = current_date_kst;
  used := coalesce(used, 0);
  return query select p_limit, greatest(0, p_limit - used), ((current_date_kst + 1)::timestamp at time zone 'Asia/Seoul');
end;
$$;

drop function if exists public.reserve_daily_chat_message(text, integer);
create or replace function public.reserve_daily_chat_message(p_request_id text, p_limit integer default 30)
returns table(allowed boolean, duplicate boolean, message_limit integer, remaining integer, reset_at timestamp with time zone, response_json jsonb)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  current_date_kst date := timezone('Asia/Seoul', now())::date;
  next_count integer;
  existing_status text;
  existing_response jsonb;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED' using errcode = '42501'; end if;
  p_limit := greatest(1, least(coalesce(p_limit, 30), 500));
  if p_request_id is null or char_length(p_request_id) < 8 or char_length(p_request_id) > 300 then raise exception 'INVALID_REQUEST_ID' using errcode = '22023'; end if;
  perform pg_advisory_xact_lock(hashtextextended(auth.uid()::text || ':' || p_request_id, 0));
  select events.status, events.response_json into existing_status, existing_response
  from public.chat_usage_events events where events.request_id = p_request_id and events.user_id = auth.uid();
  if existing_status is not null and existing_status <> 'refunded' then
    select used_count into next_count from public.chat_usage_daily where user_id = auth.uid() and usage_date = current_date_kst;
    return query select false, true, p_limit, greatest(0, p_limit - coalesce(next_count, 0)), ((current_date_kst + 1)::timestamp at time zone 'Asia/Seoul'), existing_response;
    return;
  end if;
  insert into public.chat_usage_daily (user_id, usage_date, used_count) values (auth.uid(), current_date_kst, 0) on conflict do nothing;
  update public.chat_usage_daily set used_count = used_count + 1, updated_at = timezone('utc'::text, now())
    where user_id = auth.uid() and usage_date = current_date_kst and used_count < p_limit returning used_count into next_count;
  if next_count is null then
    return query select false, false, p_limit, 0, ((current_date_kst + 1)::timestamp at time zone 'Asia/Seoul'), null::jsonb;
    return;
  end if;
  insert into public.chat_usage_events (request_id, user_id, usage_date, status)
  values (p_request_id, auth.uid(), current_date_kst, 'reserved')
  on conflict (user_id, request_id) do update
    set usage_date = excluded.usage_date, status = 'reserved', response_json = null, completed_at = null, refunded_at = null
    where public.chat_usage_events.status = 'refunded';
  return query select true, false, p_limit, greatest(0, p_limit - next_count), ((current_date_kst + 1)::timestamp at time zone 'Asia/Seoul'), null::jsonb;
end;
$$;

create or replace function public.complete_daily_chat_message(p_request_id text, p_response_json jsonb)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED' using errcode = '42501'; end if;
  if p_request_id is null or char_length(p_request_id) < 8 or char_length(p_request_id) > 300 then raise exception 'INVALID_REQUEST_ID' using errcode = '22023'; end if;
  update public.chat_usage_events
  set status = 'completed', response_json = coalesce(p_response_json, '{}'::jsonb), completed_at = timezone('utc'::text, now())
  where request_id = p_request_id and user_id = auth.uid() and status in ('reserved', 'completed');
  return found;
end;
$$;

create or replace function public.refund_daily_chat_message(p_request_id text, p_limit integer default 30)
returns table(message_limit integer, remaining integer, reset_at timestamp with time zone)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  target_date date;
  used integer := 0;
begin
  if auth.uid() is null then raise exception 'AUTH_REQUIRED' using errcode = '42501'; end if;
  p_limit := greatest(1, least(coalesce(p_limit, 30), 500));
  if p_request_id is null or char_length(p_request_id) < 8 or char_length(p_request_id) > 300 then raise exception 'INVALID_REQUEST_ID' using errcode = '22023'; end if;
  update public.chat_usage_events set status = 'refunded', refunded_at = timezone('utc'::text, now())
    where request_id = p_request_id and user_id = auth.uid() and status = 'reserved' returning usage_date into target_date;
  if target_date is not null then
    update public.chat_usage_daily set used_count = greatest(0, used_count - 1), updated_at = timezone('utc'::text, now())
      where user_id = auth.uid() and usage_date = target_date returning used_count into used;
  else
    target_date := timezone('Asia/Seoul', now())::date;
    select used_count into used from public.chat_usage_daily where user_id = auth.uid() and usage_date = target_date;
  end if;
  return query select p_limit, greatest(0, p_limit - coalesce(used, 0)), ((target_date + 1)::timestamp at time zone 'Asia/Seoul');
end;
$$;

revoke all on function public.get_daily_chat_quota(integer) from public;
revoke all on function public.reserve_daily_chat_message(text, integer) from public;
revoke all on function public.complete_daily_chat_message(text, jsonb) from public;
revoke all on function public.refund_daily_chat_message(text, integer) from public;
grant execute on function public.get_daily_chat_quota(integer) to authenticated;
grant execute on function public.reserve_daily_chat_message(text, integer) to authenticated;
grant execute on function public.complete_daily_chat_message(text, jsonb) to authenticated;
grant execute on function public.refund_daily_chat_message(text, integer) to authenticated;

-- Supabase may grant function execution to API roles through default privileges.
-- Keep callable SECURITY DEFINER functions limited to the roles that own their API contract.
revoke all on function public.apply_content_report_action(uuid, text, text) from public, anon;
grant execute on function public.apply_content_report_action(uuid, text, text) to authenticated;

revoke all on function public.get_daily_chat_quota(integer) from public, anon;
revoke all on function public.reserve_daily_chat_message(text, integer) from public, anon;
revoke all on function public.complete_daily_chat_message(text, jsonb) from public, anon;
revoke all on function public.refund_daily_chat_message(text, integer) from public, anon;
grant execute on function public.get_daily_chat_quota(integer) to authenticated;
grant execute on function public.reserve_daily_chat_message(text, integer) to authenticated;
grant execute on function public.complete_daily_chat_message(text, jsonb) to authenticated;
grant execute on function public.refund_daily_chat_message(text, integer) to authenticated;

-- Trigger functions are invoked by PostgreSQL and are not public RPC endpoints.
revoke all on function public.handle_new_profile() from public, anon, authenticated;
revoke all on function public.validate_content_report_target() from public, anon, authenticated;
revoke all on function public.quarantine_content_after_reports() from public, anon, authenticated;

-- Event-trigger functions are database-internal and must not be exposed as RPC endpoints.
do $$
begin
  if to_regprocedure('public.rls_auto_enable()') is not null then
    execute 'revoke all on function public.rls_auto_enable() from public, anon, authenticated';
  end if;
end $$;

-- Remove the retired age-attestation field and any legacy signup metadata.
update auth.users
set raw_user_meta_data = coalesce(raw_user_meta_data, '{}'::jsonb) - 'ageConfirmed'
where coalesce(raw_user_meta_data, '{}'::jsonb) ? 'ageConfirmed';
alter table public.profiles drop column if exists age_confirmed_at;

-- Additive backend stabilization. Apply before the Worker cutover.
-- No existing client privileges are removed in this phase.

-- Fail fast instead of waiting indefinitely behind production traffic, while
-- still allowing the bounded message-history backfill to complete.
set lock_timeout = '5s';
set statement_timeout = '15min';

-- Rooms retain an immutable prompt snapshot and chat history. Shared source
-- content deletion must detach those references, not delete another user's room.
alter table public.rooms alter column character_id drop not null;
alter table public.rooms alter column world_id drop not null;
alter table public.rooms drop constraint if exists rooms_character_id_fkey;
alter table public.rooms add constraint rooms_character_id_fkey
  foreign key (character_id) references public.characters (id) on delete set null not valid;
alter table public.rooms drop constraint if exists rooms_world_id_fkey;
alter table public.rooms add constraint rooms_world_id_fkey
  foreign key (world_id) references public.worlds (id) on delete set null not valid;
alter table public.rooms validate constraint rooms_character_id_fkey;
alter table public.rooms validate constraint rooms_world_id_fkey;

alter table public.chat_usage_events add column if not exists route text not null default 'room';
alter table public.chat_usage_events add column if not exists room_id uuid references public.rooms on delete cascade;
alter table public.chat_usage_events add column if not exists request_fingerprint text;
alter table public.chat_usage_events add column if not exists lease_expires_at timestamp with time zone;
alter table public.chat_usage_events add column if not exists attempt_count integer not null default 1;

alter table public.rooms add column if not exists version bigint not null default 0;
alter table public.room_messages add column if not exists sequence_no bigint;

with room_max as (
  select room_id, coalesce(max(sequence_no), 0) as max_sequence_no
  from public.room_messages
  group by room_id
), ranked as (
  select messages.id, room_max.max_sequence_no + row_number() over (
    partition by messages.room_id
    order by messages.created_at, case messages.role when 'user' then 0 when 'assistant' then 1 else 2 end, messages.id
  ) as sequence_no
  from public.room_messages messages
  join room_max on room_max.room_id = messages.room_id
  where messages.sequence_no is null
)
update public.room_messages messages
set sequence_no = ranked.sequence_no
from ranked
where messages.id = ranked.id;

create or replace function public.assign_room_message_sequence()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if new.sequence_no is null then
    perform pg_advisory_xact_lock(hashtextextended(new.room_id::text, 0));
    select coalesce(max(messages.sequence_no), 0) + 1
      into new.sequence_no
    from public.room_messages messages
    where messages.room_id = new.room_id;
  end if;
  return new;
end;
$$;

drop trigger if exists room_messages_assign_sequence on public.room_messages;
create trigger room_messages_assign_sequence
before insert on public.room_messages
for each row execute function public.assign_room_message_sequence();

alter table public.room_messages alter column sequence_no set not null;
create unique index if not exists room_messages_room_sequence_unique
  on public.room_messages (room_id, sequence_no);
create index if not exists room_messages_room_sequence
  on public.room_messages (room_id, sequence_no asc);

create or replace function public.reserve_chat_message_v2(
  p_user_id uuid,
  p_route text,
  p_room_id uuid,
  p_request_id text,
  p_request_fingerprint text,
  p_limit integer default 30,
  p_lease_seconds integer default 120
)
returns table(
  disposition text,
  allowed boolean,
  duplicate boolean,
  message_limit integer,
  remaining integer,
  reset_at timestamp with time zone,
  response_json jsonb,
  room_version bigint,
  lease_expires_at timestamp with time zone
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  current_date_kst date := timezone('Asia/Seoul', now())::date;
  next_count integer;
  existing_event public.chat_usage_events%rowtype;
  current_room_version bigint := 0;
  next_lease timestamp with time zone;
  expired_event record;
begin
  if p_user_id is null then raise exception 'AUTH_REQUIRED' using errcode = '42501'; end if;
  if p_route not in ('legacy', 'room') then raise exception 'INVALID_CHAT_ROUTE' using errcode = '22023'; end if;
  if p_route = 'room' and p_room_id is null then raise exception 'ROOM_REQUIRED' using errcode = '22023'; end if;
  if p_route = 'legacy' then p_room_id := null; end if;
  if p_request_id is null or char_length(p_request_id) < 8 or char_length(p_request_id) > 300 then raise exception 'INVALID_REQUEST_ID' using errcode = '22023'; end if;
  if p_request_fingerprint is null or char_length(p_request_fingerprint) < 16 or char_length(p_request_fingerprint) > 128 then raise exception 'INVALID_REQUEST_FINGERPRINT' using errcode = '22023'; end if;
  p_limit := greatest(1, least(coalesce(p_limit, 30), 500));
  p_lease_seconds := greatest(30, least(coalesce(p_lease_seconds, 120), 600));
  next_lease := timezone('utc'::text, now()) + make_interval(secs => p_lease_seconds);

  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text || ':' || p_request_id, 0));
  if p_room_id is not null then
    perform pg_advisory_xact_lock(hashtextextended('room:' || p_room_id::text, 0));
    select rooms.version into current_room_version
    from public.rooms rooms
    where rooms.id = p_room_id and rooms.user_id = p_user_id;
    if not found then raise exception 'ROOM_NOT_FOUND' using errcode = 'P0002'; end if;

    if exists (
      select 1 from public.chat_usage_events events
      where events.user_id = p_user_id
        and events.room_id = p_room_id
        and events.status = 'reserved'
        and events.request_id <> p_request_id
        and events.lease_expires_at > timezone('utc'::text, now())
    ) then
      select used_count into next_count from public.chat_usage_daily where user_id = p_user_id and usage_date = current_date_kst;
      return query select 'in_progress'::text, false, true, p_limit,
        greatest(0, p_limit - coalesce(next_count, 0)),
        ((current_date_kst + 1)::timestamp at time zone 'Asia/Seoul'), null::jsonb,
        current_room_version, null::timestamp with time zone;
      return;
    end if;
  end if;

  select events.* into existing_event
  from public.chat_usage_events events
  where events.user_id = p_user_id and events.request_id = p_request_id
  for update;

  if found then
    select used_count into next_count from public.chat_usage_daily where user_id = p_user_id and usage_date = current_date_kst;
    if existing_event.request_fingerprint is distinct from p_request_fingerprint
      or existing_event.route is distinct from p_route
      or existing_event.room_id is distinct from p_room_id then
      return query select 'conflict'::text, false, true, p_limit,
        greatest(0, p_limit - coalesce(next_count, 0)),
        ((current_date_kst + 1)::timestamp at time zone 'Asia/Seoul'), null::jsonb,
        current_room_version, existing_event.lease_expires_at;
      return;
    end if;
    if existing_event.status = 'completed' then
      return query select 'replay'::text, false, true, p_limit,
        greatest(0, p_limit - coalesce(next_count, 0)),
        ((current_date_kst + 1)::timestamp at time zone 'Asia/Seoul'), existing_event.response_json,
        current_room_version, existing_event.lease_expires_at;
      return;
    end if;
    if existing_event.status = 'reserved' and existing_event.lease_expires_at > timezone('utc'::text, now()) then
      return query select 'in_progress'::text, false, true, p_limit,
        greatest(0, p_limit - coalesce(next_count, 0)),
        ((current_date_kst + 1)::timestamp at time zone 'Asia/Seoul'), null::jsonb,
        current_room_version, existing_event.lease_expires_at;
      return;
    end if;
    if existing_event.status = 'reserved' and existing_event.attempt_count >= 2 then
      update public.chat_usage_events
      set status = 'refunded',
          refunded_at = timezone('utc'::text, now()),
          lease_expires_at = null
      where user_id = p_user_id and request_id = p_request_id and status = 'reserved';
      if found then
        update public.chat_usage_daily
        set used_count = greatest(0, used_count - 1), updated_at = timezone('utc'::text, now())
        where user_id = p_user_id and usage_date = existing_event.usage_date
        returning used_count into next_count;
      end if;
      return query select 'conflict'::text, false, true, p_limit,
        greatest(0, p_limit - coalesce(next_count, 0)),
        ((current_date_kst + 1)::timestamp at time zone 'Asia/Seoul'), null::jsonb,
        current_room_version, null::timestamp with time zone;
      return;
    end if;
    if existing_event.status = 'reserved' then
      update public.chat_usage_events
      set lease_expires_at = next_lease,
          attempt_count = attempt_count + 1
      where user_id = p_user_id and request_id = p_request_id;
      return query select 'reserved'::text, true, false, p_limit,
        greatest(0, p_limit - coalesce(next_count, 0)),
        ((current_date_kst + 1)::timestamp at time zone 'Asia/Seoul'), null::jsonb,
        current_room_version, next_lease;
      return;
    end if;
    if existing_event.status = 'refunded' and existing_event.attempt_count >= 2 then
      return query select 'conflict'::text, false, true, p_limit,
        greatest(0, p_limit - coalesce(next_count, 0)),
        ((current_date_kst + 1)::timestamp at time zone 'Asia/Seoul'), null::jsonb,
        current_room_version, null::timestamp with time zone;
      return;
    end if;
  end if;

  -- A new reservation opportunistically refunds a bounded batch of this user's expired leases.
  for expired_event in
    select events.user_id, events.request_id, events.usage_date
    from public.chat_usage_events events
    where events.user_id = p_user_id
      and events.request_id <> p_request_id
      and events.status = 'reserved'
      and events.lease_expires_at <= timezone('utc'::text, now())
    order by events.lease_expires_at asc
    limit 20
    for update skip locked
  loop
    update public.chat_usage_events
    set status = 'refunded', refunded_at = timezone('utc'::text, now()), lease_expires_at = null
    where user_id = expired_event.user_id
      and request_id = expired_event.request_id
      and status = 'reserved';
    if found then
      update public.chat_usage_daily
      set used_count = greatest(0, used_count - 1), updated_at = timezone('utc'::text, now())
      where user_id = expired_event.user_id and usage_date = expired_event.usage_date;
    end if;
  end loop;

  insert into public.chat_usage_daily (user_id, usage_date, used_count)
  values (p_user_id, current_date_kst, 0)
  on conflict do nothing;
  next_count := null;
  update public.chat_usage_daily
  set used_count = used_count + 1, updated_at = timezone('utc'::text, now())
  where user_id = p_user_id and usage_date = current_date_kst and used_count < p_limit
  returning used_count into next_count;
  if next_count is null then
    return query select 'limit_exceeded'::text, false, false, p_limit, 0,
      ((current_date_kst + 1)::timestamp at time zone 'Asia/Seoul'), null::jsonb,
      current_room_version, null::timestamp with time zone;
    return;
  end if;

  insert into public.chat_usage_events (
    request_id, user_id, usage_date, status, route, room_id,
    request_fingerprint, lease_expires_at, attempt_count,
    response_json, completed_at, refunded_at
  ) values (
    p_request_id, p_user_id, current_date_kst, 'reserved', p_route, p_room_id,
    p_request_fingerprint, next_lease, 1, null, null, null
  )
  on conflict (user_id, request_id) do update
  set usage_date = excluded.usage_date,
      status = 'reserved',
      route = excluded.route,
      room_id = excluded.room_id,
      request_fingerprint = excluded.request_fingerprint,
      lease_expires_at = excluded.lease_expires_at,
      attempt_count = public.chat_usage_events.attempt_count + 1,
      response_json = null,
      completed_at = null,
      refunded_at = null
  where public.chat_usage_events.status = 'refunded';

  return query select 'reserved'::text, true, false, p_limit,
    greatest(0, p_limit - next_count),
    ((current_date_kst + 1)::timestamp at time zone 'Asia/Seoul'), null::jsonb,
    current_room_version, next_lease;
end;
$$;

create or replace function public.complete_legacy_chat_message_v2(
  p_user_id uuid,
  p_request_id text,
  p_request_fingerprint text,
  p_response_json jsonb
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text || ':' || p_request_id, 0));
  update public.chat_usage_events
  set status = 'completed',
      response_json = coalesce(p_response_json, '{}'::jsonb),
      completed_at = timezone('utc'::text, now()),
      lease_expires_at = null
  where user_id = p_user_id
    and request_id = p_request_id
    and request_fingerprint = p_request_fingerprint
    and route = 'legacy'
    and status = 'reserved'
    and lease_expires_at > timezone('utc'::text, now());
  if not found then raise exception 'CHAT_RESERVATION_EXPIRED' using errcode = '40001'; end if;
  return true;
end;
$$;

create or replace function public.refund_chat_message_v2(
  p_user_id uuid,
  p_request_id text,
  p_request_fingerprint text,
  p_limit integer default 30
)
returns table(message_limit integer, remaining integer, reset_at timestamp with time zone)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  target_date date;
  used integer := 0;
begin
  p_limit := greatest(1, least(coalesce(p_limit, 30), 500));
  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text || ':' || p_request_id, 0));
  update public.chat_usage_events
  set status = 'refunded', refunded_at = timezone('utc'::text, now()), lease_expires_at = null
  where user_id = p_user_id
    and request_id = p_request_id
    and request_fingerprint = p_request_fingerprint
    and status = 'reserved'
  returning usage_date into target_date;
  if target_date is not null then
    update public.chat_usage_daily
    set used_count = greatest(0, used_count - 1), updated_at = timezone('utc'::text, now())
    where user_id = p_user_id and usage_date = target_date
    returning used_count into used;
  else
    target_date := timezone('Asia/Seoul', now())::date;
    select used_count into used from public.chat_usage_daily where user_id = p_user_id and usage_date = target_date;
  end if;
  return query select p_limit, greatest(0, p_limit - coalesce(used, 0)), ((target_date + 1)::timestamp at time zone 'Asia/Seoul');
end;
$$;

create or replace function public.create_room_v2(
  p_user_id uuid,
  p_character_slug text,
  p_world_slug text,
  p_user_alias text,
  p_title text,
  p_bridge_profile jsonb,
  p_prompt_snapshot jsonb,
  p_state jsonb,
  p_greeting jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  target_character public.characters%rowtype;
  target_world public.worlds%rowtype;
  created_room public.rooms%rowtype;
begin
  select * into target_character from public.characters where slug = p_character_slug;
  if not found then raise exception 'ROOM_TARGET_NOT_FOUND' using errcode = 'P0002'; end if;
  if target_character.owner_user_id <> p_user_id
    and not (target_character.visibility = 'public' and target_character.display_status = 'visible') then
    raise exception 'ROOM_TARGET_NOT_FOUND' using errcode = 'P0002';
  end if;
  if target_character.display_status = 'hidden' or exists (
    select 1 from public.content_moderation moderation
    where moderation.entity_type = 'character' and moderation.entity_id = target_character.id
      and moderation.status in ('quarantined', 'blocked')
  ) then raise exception 'ROOM_TARGET_NOT_STARTABLE' using errcode = '22023'; end if;

  if nullif(btrim(coalesce(p_world_slug, '')), '') is not null then
    select * into target_world from public.worlds where slug = p_world_slug;
    if not found then raise exception 'ROOM_TARGET_NOT_FOUND' using errcode = 'P0002'; end if;
    if target_world.owner_user_id <> p_user_id
      and not (target_world.visibility = 'public' and target_world.display_status = 'visible') then
      raise exception 'ROOM_TARGET_NOT_FOUND' using errcode = 'P0002';
    end if;
    if target_world.display_status = 'hidden' or exists (
      select 1 from public.content_moderation moderation
      where moderation.entity_type = 'world' and moderation.entity_id = target_world.id
        and moderation.status in ('quarantined', 'blocked')
    ) then raise exception 'ROOM_TARGET_NOT_STARTABLE' using errcode = '22023'; end if;
  end if;

  insert into public.rooms (
    user_id, character_id, world_id, user_alias, title,
    bridge_profile_json, resolved_prompt_snapshot_json, last_message_at, version
  ) values (
    p_user_id, target_character.id, target_world.id, left(coalesce(nullif(btrim(p_user_alias), ''), '나'), 40),
    left(coalesce(p_title, target_character.name), 200), coalesce(p_bridge_profile, '{}'::jsonb),
    coalesce(p_prompt_snapshot, '{}'::jsonb), timezone('utc'::text, now()), 0
  ) returning * into created_room;

  insert into public.room_state_summaries (
    room_id, current_situation, location, relationship_state,
    inventory_json, appearance_json, pose_json, future_promises_json, world_notes_json
  ) values (
    created_room.id, p_state ->> 'currentSituation', p_state ->> 'location', p_state ->> 'relationshipState',
    coalesce(p_state -> 'inventory', '[]'::jsonb), coalesce(p_state -> 'appearance', '[]'::jsonb),
    coalesce(p_state -> 'pose', '[]'::jsonb), coalesce(p_state -> 'futurePromises', '[]'::jsonb),
    coalesce(p_state -> 'worldNotes', '[]'::jsonb)
  );
  insert into public.room_messages (room_id, role, content_json, sequence_no)
  values (created_room.id, 'assistant', coalesce(p_greeting, '{}'::jsonb), 1);
  update public.characters set chat_start_count = chat_start_count + 1 where id = target_character.id;
  if target_world.id is not null then update public.worlds set chat_start_count = chat_start_count + 1 where id = target_world.id; end if;
  return jsonb_build_object('room_id', created_room.id, 'version', created_room.version);
end;
$$;

create or replace function public.commit_room_turn_v2(
  p_user_id uuid,
  p_room_id uuid,
  p_request_id text,
  p_request_fingerprint text,
  p_expected_version bigint,
  p_user_content jsonb,
  p_assistant_content jsonb,
  p_next_state jsonb,
  p_next_prompt_snapshot jsonb,
  p_response_json jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  target_room public.rooms%rowtype;
  reservation public.chat_usage_events%rowtype;
  next_sequence bigint;
begin
  perform pg_advisory_xact_lock(hashtextextended('room:' || p_room_id::text, 0));
  select * into target_room from public.rooms where id = p_room_id and user_id = p_user_id for update;
  if not found then raise exception 'ROOM_NOT_FOUND' using errcode = 'P0002'; end if;
  if target_room.version <> p_expected_version then raise exception 'CHAT_ROOM_VERSION_CONFLICT' using errcode = '40001'; end if;
  select * into reservation from public.chat_usage_events
  where user_id = p_user_id and request_id = p_request_id for update;
  if not found
    or reservation.status <> 'reserved'
    or reservation.route <> 'room'
    or reservation.room_id is distinct from p_room_id
    or reservation.request_fingerprint is distinct from p_request_fingerprint
    or reservation.lease_expires_at <= timezone('utc'::text, now()) then
    raise exception 'CHAT_RESERVATION_EXPIRED' using errcode = '40001';
  end if;
  select coalesce(max(sequence_no), 0) + 1 into next_sequence from public.room_messages where room_id = p_room_id;
  insert into public.room_messages (room_id, role, content_json, sequence_no) values
    (p_room_id, 'user', coalesce(p_user_content, '{}'::jsonb), next_sequence),
    (p_room_id, 'assistant', coalesce(p_assistant_content, '{}'::jsonb), next_sequence + 1);
  insert into public.room_state_summaries (
    room_id, current_situation, location, relationship_state,
    inventory_json, appearance_json, pose_json, future_promises_json, world_notes_json, updated_at
  ) values (
    p_room_id, p_next_state ->> 'currentSituation', p_next_state ->> 'location', p_next_state ->> 'relationshipState',
    coalesce(p_next_state -> 'inventory', '[]'::jsonb), coalesce(p_next_state -> 'appearance', '[]'::jsonb),
    coalesce(p_next_state -> 'pose', '[]'::jsonb), coalesce(p_next_state -> 'futurePromises', '[]'::jsonb),
    coalesce(p_next_state -> 'worldNotes', '[]'::jsonb), timezone('utc'::text, now())
  )
  on conflict (room_id) do update set
    current_situation = excluded.current_situation,
    location = excluded.location,
    relationship_state = excluded.relationship_state,
    inventory_json = excluded.inventory_json,
    appearance_json = excluded.appearance_json,
    pose_json = excluded.pose_json,
    future_promises_json = excluded.future_promises_json,
    world_notes_json = excluded.world_notes_json,
    updated_at = excluded.updated_at;
  update public.rooms set
    resolved_prompt_snapshot_json = coalesce(p_next_prompt_snapshot, resolved_prompt_snapshot_json),
    version = version + 1,
    updated_at = timezone('utc'::text, now()),
    last_message_at = timezone('utc'::text, now())
  where id = p_room_id;
  update public.chat_usage_events set
    status = 'completed', response_json = coalesce(p_response_json, '{}'::jsonb),
    completed_at = timezone('utc'::text, now()), lease_expires_at = null
  where user_id = p_user_id and request_id = p_request_id;
  return jsonb_build_object('room_id', p_room_id, 'version', target_room.version + 1);
end;
$$;

create or replace function public.reconcile_expired_chat_reservations_v2(p_limit integer default 100)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  target record;
  reconciled_count integer := 0;
begin
  p_limit := greatest(1, least(coalesce(p_limit, 100), 1000));
  for target in
    select events.user_id, events.request_id, events.usage_date
    from public.chat_usage_events events
    where events.status = 'reserved' and events.lease_expires_at <= timezone('utc'::text, now())
    order by events.lease_expires_at asc
    limit p_limit
    for update skip locked
  loop
    update public.chat_usage_events set
      status = 'refunded', refunded_at = timezone('utc'::text, now()), lease_expires_at = null
    where user_id = target.user_id and request_id = target.request_id and status = 'reserved';
    if found then
      update public.chat_usage_daily set
        used_count = greatest(0, used_count - 1), updated_at = timezone('utc'::text, now())
      where user_id = target.user_id and usage_date = target.usage_date;
      reconciled_count := reconciled_count + 1;
    end if;
  end loop;
  return jsonb_build_object('reconciled', reconciled_count);
end;
$$;

revoke all on function public.assign_room_message_sequence() from public, anon, authenticated;
revoke all on function public.reserve_chat_message_v2(uuid, text, uuid, text, text, integer, integer) from public, anon, authenticated;
revoke all on function public.complete_legacy_chat_message_v2(uuid, text, text, jsonb) from public, anon, authenticated;
revoke all on function public.refund_chat_message_v2(uuid, text, text, integer) from public, anon, authenticated;
revoke all on function public.create_room_v2(uuid, text, text, text, text, jsonb, jsonb, jsonb, jsonb) from public, anon, authenticated;
revoke all on function public.commit_room_turn_v2(uuid, uuid, text, text, bigint, jsonb, jsonb, jsonb, jsonb, jsonb) from public, anon, authenticated;
revoke all on function public.reconcile_expired_chat_reservations_v2(integer) from public, anon, authenticated;
grant execute on function public.reserve_chat_message_v2(uuid, text, uuid, text, text, integer, integer) to service_role;
grant execute on function public.complete_legacy_chat_message_v2(uuid, text, text, jsonb) to service_role;
grant execute on function public.refund_chat_message_v2(uuid, text, text, integer) to service_role;
grant execute on function public.create_room_v2(uuid, text, text, text, text, jsonb, jsonb, jsonb, jsonb) to service_role;
grant execute on function public.commit_room_turn_v2(uuid, uuid, text, text, bigint, jsonb, jsonb, jsonb, jsonb, jsonb) to service_role;
grant execute on function public.reconcile_expired_chat_reservations_v2(integer) to service_role;

create or replace function public.tags_within_contract(p_tags text[])
returns boolean
language sql
immutable
set search_path = public, pg_temp
as $$
  select coalesce(cardinality(p_tags), 0) <= 12
    and coalesce((select bool_and(char_length(btrim(tag)) between 1 and 32) from unnest(coalesce(p_tags, '{}'::text[])) tag), true);
$$;

alter table public.characters drop constraint if exists characters_backend_input_contract;
alter table public.characters add constraint characters_backend_input_contract check (
  char_length(btrim(name)) between 1 and 80
  and char_length(coalesce(headline, '')) <= 160
  and char_length(summary) <= 4000
  and public.tags_within_contract(tags)
  and octet_length(profile_json::text) <= 16384
  and octet_length(speech_style_json::text) <= 16384
  and octet_length(prompt_profile_json::text) <= 16384
  and (source_type <> 'derivative' or (btrim(coalesce(source_url, '')) ~ '^https://' and char_length(btrim(coalesce(source_url, ''))) <= 2048))
  and (
    visibility <> 'public'
    or created_at < timestamptz '2026-07-01 00:00:00+00'
    or (rights_attested_at is not null and nullif(btrim(coalesce(cover_image_url, '')), '') is not null)
  )
) not valid;

alter table public.worlds drop constraint if exists worlds_backend_input_contract;
alter table public.worlds add constraint worlds_backend_input_contract check (
  char_length(btrim(name)) between 1 and 80
  and char_length(coalesce(headline, '')) <= 160
  and char_length(summary) <= 4000
  and char_length(coalesce(world_rules_markdown, '')) <= 8000
  and public.tags_within_contract(tags)
  and octet_length(prompt_profile_json::text) <= 16384
  and (source_type <> 'derivative' or (btrim(coalesce(source_url, '')) ~ '^https://' and char_length(btrim(coalesce(source_url, ''))) <= 2048))
  and (
    visibility <> 'public'
    or created_at < timestamptz '2026-07-01 00:00:00+00'
    or (rights_attested_at is not null and nullif(btrim(coalesce(cover_image_url, '')), '') is not null)
  )
) not valid;

-- Client reads remain RLS-scoped while all mutations move behind the Worker.
grant select on public.characters, public.worlds, public.character_assets, public.world_assets to anon, authenticated;
grant select on public.rooms, public.room_messages, public.room_state_summaries to authenticated;

-- Durable cleanup intent for content deletions. The subject UUID deliberately
-- has no auth.users foreign key so retries survive the row being deleted.
create table if not exists public.storage_deletion_outbox (
  id uuid primary key default gen_random_uuid(),
  operation_key text not null unique check (char_length(operation_key) between 1 and 200),
  operation_kind text not null check (operation_kind = 'content'),
  subject_user_id uuid not null,
  entity_type text check (entity_type in ('character', 'world')),
  entity_id uuid,
  object_paths text[] not null default '{}',
  status text not null default 'prepared',
  lease_expires_at timestamp with time zone,
  attempt_count integer not null default 0 check (attempt_count >= 0),
  last_error_code text check (last_error_code is null or char_length(last_error_code) <= 64),
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now()),
  completed_at timestamp with time zone,
  check (cardinality(object_paths) <= 10000),
  constraint storage_deletion_outbox_status_valid check (status in ('prepared', 'processing', 'completed')),
  constraint storage_deletion_outbox_lease_valid check ((status = 'processing') = (lease_expires_at is not null)),
  check (entity_type is not null and entity_id is not null)
);

alter table public.storage_deletion_outbox add column if not exists lease_expires_at timestamp with time zone;
alter table public.storage_deletion_outbox drop constraint if exists storage_deletion_outbox_status_check;
alter table public.storage_deletion_outbox drop constraint if exists storage_deletion_outbox_status_valid;
alter table public.storage_deletion_outbox drop constraint if exists storage_deletion_outbox_lease_valid;
update public.storage_deletion_outbox
set status = 'prepared', lease_expires_at = null
where status not in ('prepared', 'processing', 'completed')
   or (status = 'processing' and lease_expires_at is null);
alter table public.storage_deletion_outbox
  add constraint storage_deletion_outbox_status_valid check (status in ('prepared', 'processing', 'completed'));
alter table public.storage_deletion_outbox
  add constraint storage_deletion_outbox_lease_valid check ((status = 'processing') = (lease_expires_at is not null));

drop index if exists public.storage_deletion_outbox_pending_created;
create index if not exists storage_deletion_outbox_pending_updated
  on public.storage_deletion_outbox (updated_at, id)
  where status <> 'completed';

alter table public.storage_deletion_outbox enable row level security;
revoke all on table public.storage_deletion_outbox from public, anon, authenticated;
grant select, insert, update, delete on table public.storage_deletion_outbox to service_role;

-- A deletion fence prevents new signed upload URLs from escaping while an
-- account prefix is being removed. It survives auth.users deletion so the
-- scheduled Worker can remove uploads made with already-issued URLs until
-- every pre-fence URL has expired.
create table if not exists public.account_storage_cleanup_fences (
  user_id uuid primary key,
  cleanup_until timestamp with time zone not null,
  attempt_count integer not null default 0 check (attempt_count >= 0),
  last_error_code text check (last_error_code is null or char_length(last_error_code) <= 64),
  last_scan_at timestamp with time zone,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now())
);

create index if not exists account_storage_cleanup_fences_due
  on public.account_storage_cleanup_fences (cleanup_until, user_id);

alter table public.account_storage_cleanup_fences enable row level security;
revoke all on table public.account_storage_cleanup_fences from public, anon, authenticated;
grant select, insert, update, delete on table public.account_storage_cleanup_fences to service_role;

create or replace function public.begin_account_storage_cleanup_v1(
  p_user_id uuid,
  p_cleanup_until timestamp with time zone
)
returns timestamp with time zone
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  effective_cleanup_until timestamp with time zone;
begin
  if p_user_id is null
    or p_cleanup_until <= timezone('utc'::text, now())
    or p_cleanup_until > timezone('utc'::text, now()) + interval '3 hours' then
    raise exception 'INVALID_ACCOUNT_STORAGE_CLEANUP_FENCE' using errcode = '22023';
  end if;

  insert into public.account_storage_cleanup_fences (user_id, cleanup_until)
  values (p_user_id, p_cleanup_until)
  on conflict (user_id) do update set
    cleanup_until = greatest(
      public.account_storage_cleanup_fences.cleanup_until,
      excluded.cleanup_until
    ),
    updated_at = timezone('utc'::text, now())
  returning cleanup_until into effective_cleanup_until;

  return effective_cleanup_until;
end;
$$;

revoke all on function public.begin_account_storage_cleanup_v1(uuid, timestamp with time zone)
  from public, anon, authenticated;
grant execute on function public.begin_account_storage_cleanup_v1(uuid, timestamp with time zone)
  to service_role;

-- chat_messages predates the cascading user-owned tables. Delete only that
-- legacy blocker inside the same auth.users transaction; all other user data
-- continues to use its declared FK cascades.
create or replace function public.cleanup_legacy_user_rows_before_auth_delete()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  delete from public.chat_messages where user_id = old.id;
  return old;
end;
$$;

drop trigger if exists auth_user_cleanup_legacy_rows on auth.users;
create trigger auth_user_cleanup_legacy_rows
before delete on auth.users
for each row execute function public.cleanup_legacy_user_rows_before_auth_delete();

revoke all on function public.cleanup_legacy_user_rows_before_auth_delete()
  from public, anon, authenticated, service_role;

reset statement_timeout;
reset lock_timeout;

-- Apply only after the v2 Worker is serving production traffic.
-- Roll back the Worker forward; do not restore these direct mutation grants.

revoke all on function public.reserve_daily_chat_message(text, integer) from public, anon, authenticated;
revoke all on function public.complete_daily_chat_message(text, jsonb) from public, anon, authenticated;
revoke all on function public.refund_daily_chat_message(text, integer) from public, anon, authenticated;

revoke insert, update, delete on public.characters from anon, authenticated;
revoke insert, update, delete on public.worlds from anon, authenticated;
revoke insert, update, delete on public.character_assets from anon, authenticated;
revoke insert, update, delete on public.world_assets from anon, authenticated;
revoke insert, update, delete on public.rooms from anon, authenticated;
revoke insert, update, delete on public.room_messages from anon, authenticated;
revoke insert, update, delete on public.room_state_summaries from anon, authenticated;

drop policy if exists "Users can insert their own characters" on public.characters;
drop policy if exists "Users can update their own characters" on public.characters;
drop policy if exists "Users can delete their own characters" on public.characters;
drop policy if exists "Owner users can manage all characters" on public.characters;
drop policy if exists "Users can insert their own worlds" on public.worlds;
drop policy if exists "Users can update their own worlds" on public.worlds;
drop policy if exists "Users can delete their own worlds" on public.worlds;
drop policy if exists "Owner users can manage all worlds" on public.worlds;
drop policy if exists "Users can insert their own character assets" on public.character_assets;
drop policy if exists "Users can update their own character assets" on public.character_assets;
drop policy if exists "Users can delete their own character assets" on public.character_assets;
drop policy if exists "Users can insert their own world assets" on public.world_assets;
drop policy if exists "Users can update their own world assets" on public.world_assets;
drop policy if exists "Users can delete their own world assets" on public.world_assets;
drop policy if exists "Users can insert their own rooms" on public.rooms;
drop policy if exists "Users can update their own rooms" on public.rooms;
drop policy if exists "Users can insert messages in their own rooms" on public.room_messages;
drop policy if exists "Users can write room state summaries in their own rooms" on public.room_state_summaries;

drop policy if exists "Authenticated users can upload vmate assets to their own folder" on storage.objects;
drop policy if exists "Authenticated users can update vmate assets in their own folder" on storage.objects;
drop policy if exists "Authenticated users can delete vmate assets in their own folder" on storage.objects;

revoke all on function public.reserve_chat_message_v2(uuid, text, uuid, text, text, integer, integer) from public, anon, authenticated;
revoke all on function public.complete_legacy_chat_message_v2(uuid, text, text, jsonb) from public, anon, authenticated;
revoke all on function public.refund_chat_message_v2(uuid, text, text, integer) from public, anon, authenticated;
revoke all on function public.create_room_v2(uuid, text, text, text, text, jsonb, jsonb, jsonb, jsonb) from public, anon, authenticated;
revoke all on function public.commit_room_turn_v2(uuid, uuid, text, text, bigint, jsonb, jsonb, jsonb, jsonb, jsonb) from public, anon, authenticated;
revoke all on function public.reconcile_expired_chat_reservations_v2(integer) from public, anon, authenticated;
grant execute on function public.reserve_chat_message_v2(uuid, text, uuid, text, text, integer, integer) to service_role;
grant execute on function public.complete_legacy_chat_message_v2(uuid, text, text, jsonb) to service_role;
grant execute on function public.refund_chat_message_v2(uuid, text, text, integer) to service_role;
grant execute on function public.create_room_v2(uuid, text, text, text, text, jsonb, jsonb, jsonb, jsonb) to service_role;
grant execute on function public.commit_room_turn_v2(uuid, uuid, text, text, bigint, jsonb, jsonb, jsonb, jsonb, jsonb) to service_role;
grant execute on function public.reconcile_expired_chat_reservations_v2(integer) to service_role;
