select pg_catalog.jsonb_build_object(
  'account_storage_cleanup_fences', (select count(*) from public.account_storage_cleanup_fences),
  'app_settings', (select count(*) from public.app_settings),
  'auth_users', (select count(*) from auth.users),
  'bookmarks', (select count(*) from public.bookmarks),
  'character_assets', (select count(*) from public.character_assets),
  'characters', (select count(*) from public.characters),
  'chat_messages', (select count(*) from public.chat_messages),
  'chat_usage_daily', (select count(*) from public.chat_usage_daily),
  'chat_usage_events', (select count(*) from public.chat_usage_events),
  'content_moderation', (select count(*) from public.content_moderation),
  'content_moderation_actions', (select count(*) from public.content_moderation_actions),
  'content_reports', (select count(*) from public.content_reports),
  'owner_users', (select count(*) from public.owner_users),
  'profiles', (select count(*) from public.profiles),
  'recent_views', (select count(*) from public.recent_views),
  'room_messages', (select count(*) from public.room_messages),
  'room_state_summaries', (select count(*) from public.room_state_summaries),
  'rooms', (select count(*) from public.rooms),
  'storage_deletion_outbox', (select count(*) from public.storage_deletion_outbox),
  'storage_objects', (select count(*) from storage.objects),
  'world_assets', (select count(*) from public.world_assets),
  'worlds', (select count(*) from public.worlds)
) as row_counts;
